ScofieldAsg5Dealer/Models/Car.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace ScofieldAsg10Cars.Models
{
    public class Car
    {
        public int ID { get; set; }
        public string MakeModel { get; set; }
        public int Year { get; set; }
        public int Price { get; set; }
        public int Mileage { get; set; }
        public string Color { get; set; }

    }
}

ScofieldAsg5Dealer/Areas/Admin/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ScofieldAsg10Cars.Models;


namespace ScofieldAsg10Cars.Areas.Admin.Controllers
{
    public class CarController : Controller
    {

        private CarContext context { get; set; }
        public CarController(CarContext ctx)
        {
            context = ctx;
        }

        [Area("Admin")]
        public IActionResult Index()
        {
            return View();

        }

        [Route("admin/car/list")]
        public IActionResult List()//C:\Users\16740073\source\repos\ScofieldAsg5Dealer\ScofieldAsg5Dealer\Areas\Admin\Views\Car\List.cshtml
        {
            var cars = context.Cars.OrderBy(c => c.Year).ToList();

            // return Content("Cars  List");
            return View("~/Areas/Admin/Views/Car/List.cshtml", cars);
        }

        //[HttpGet]
        public IActionResult Add()
        {
            Car car = new Car();

            ViewBag.Action = "Add";

            return View("~/Areas/Admin/Views/Car/AddUpdate.cshtml", car);
        }

    }
}

ScofieldAsg5Dealer/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ScofieldAsg10Cars.Models;
using Microsoft.EntityFrameworkCore;

namespace ScofieldAsg10Cars.Controllers
{
    public class CarController : Controller
    {
        private CarContext context { get; set; }
        public CarController(CarContext ctx)
        {
            context = ctx;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Detail(int id)
        {
            var car = context.Cars.Find(id);
            return View(car);
        }

        [Route("/cars")]    // URL:  https://localhost:5001/cars
        public IActionResult List()
        {
            var cars = context.Cars.OrderBy(c => c.Year).ToList();
            return View(cars);
        }

        [Route("cars/list/{orderby?}")]  // URL:  https://localhost:5001/cars/list/color
        public IActionResult List(string orderby)
        {
            // Andy:  Check for null
            if (orderby == null)
                orderby = "";

            //MakeModel, Year, Price, Milage, Color
            CarContext.SortOrder sortOrder;
            sortOrder = CarContext.SortOrder.Year;


            orderby = orderby.ToLower();
            switch (orderby)
            {
                case "id":
                    sortOrder = CarContext.SortOrder.ID;
                    break;
                case "make":
                    sortOrder = CarContext.SortOrder.MakeModel;
                    break;
                case "mileage":
                    sortOrder = CarContext.SortOrder.Mileage;
                    break;
                case "price":
                    sortOrder = CarContext.SortOrder.Price;
                    break;
                case "color":
                    sortOrder = CarContext.SortOrder.Color;
                    break;
                case "year":
                    sortOrder = CarContext.SortOrder.Year;
                    break;
            }

            List<Car> sortedCars = CarContext.sortBy(sortOrder, true);
            return View(sortedCars);
        }



        public IActionResult Search(String id)
        {
            List<Car> foundCars = CarContext.GetCarByMakeModel(id);
            return View(foundCars);
        }
    }
}

ScofieldAsg5Dealer/Views/Car/Detail.cshtml
@model Car
@{
    ViewBag.Title = "Car Detail";
}

<h1>Car Detail</h1>
<table class="table-bordered table-striped">
    <tr>
        <td>ID</td>
        <td>@Model.ID</td>
    </tr>
    <tr>
        <td>MakeModel</td>
        <td>@Model.MakeModel</td>
    </tr>
    <tr>
        <td>Year</td>
        <td>@Model.Year</td>
    </tr>
    <tr>
        <td>Price</td>
        <td>@Model.Price.ToString("C")</td>
    </tr>
    <tr>
        <td>Mileage</td>
        <td>@Model.Mileage.ToString("N0")</td>
    </tr>
    <tr>
        <td>Color</td>
        <td>@Model.Color</td>
    </tr>
</table>
<a class="btn btn-primary" asp-controller="Home" asp-action="Index">Home</a>
&nbsp;
<a class="btn btn-outline-secondary" asp-controller="Car" asp-action="List">Back</a>

ScofieldAsg5Dealer/Views/Car/List.cshtml
@model List<Car>
@{
    ViewBag.Title = "Car List";
}

<h1>Car List (non admin)</h1>
<div>
    <h3>Search cars by make/model:</h3>
    <form method="post" asp-controller="Car" asp-action="Search">
        <input type="text" name="id" />
        <input type="submit" value="Search" />
    </form>
</div>

<table class="table-bordered table-striped">
    <thead>
        <tr>
            <th>
                <a asp-action="List" asp-route-orderby="year">Year</a>
            </th>
            <th>
                <a asp-action="List" asp-route-orderby="make">Make and Model</a>
            </th>

            <th>
                <a asp-action="List" asp-route-orderby="price">Price</a>
            </th>
            <th>
                <a asp-action="List" asp-route-orderby="mileage">Mileage</a>
            </th>
            <th><a asp-action="List" asp-route-orderby="color">Color</a></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var car in @Model)
        {
        <tr>
            <td>@car.Year</td>
            <td>@car.MakeModel</td>
            <td>@car.Price.ToString("C")</td>
            <td>@car.Mileage.ToString("N0")</td>
            <td>@car.Color</td>

            <td>
                <a class="btn btn-primary" asp-controller="Car" asp-action="Detail"
                   asp-route-id="@car.ID">View</a>
            </td>

        </tr>
        }
    </tbody>
</table>
<a class="btn btn-primary" asp-controller="Home" asp-action="Index">Home</a>

ScofieldAsg5Dealer/Views/Car/Search.cshtml
@model List<Car>
@{
    ViewBag.Title = "Car Search";
}

<h1>Car List</h1>

<table class="table-bordered table-striped">
    <thead>
        <tr>
            <th>
                <a asp-action="List" asp-route-orderby="id">ID</a>
            </th>
            <th>
                <a asp-action="List" asp-route-orderby="year">Year</a>
            </th>
            <th>
                <a asp-action="List" asp-route-orderby="make">Make and Model</a>
            </th>

            <th>
                <a asp-action="List" asp-route-orderby="price">Price</a>
            </th>
            <th>
                <a asp-action="List" asp-route-orderby="mileage">Mileage</a>
            </th>
            <th><a asp-action="List" asp-route-orderby="color">Color</a></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var car in @Model)
        {
        <tr>
            <td>@car.ID</td>
            <td>@car.Year</td>
            <td>@car.MakeModel</td>
            <td>@car.Price.ToString("C")</td>
            <td>@car.Mileage.ToString("N0")</td>
            <td>@car.Color</td>

            <td>
                <a class="btn btn-primary" asp-controller="Car" asp-action="Detail"
                   asp-route-id="@car.ID">View</a>
            </td>

        </tr>
        }
    </tbody>
</table>
<a class="btn btn-primary" asp-controller="Home" asp-action="Index">Home</a>
<a class="btn btn-outline-secondary" asp-controller="Car" asp-action="List">Back</a>